"""Required foreign keys

Revision ID: 39d811a319e9
Revises: 6ba43edbc8b1
Create Date: 2022-07-24 15:27:49.683779

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39d811a319e9"
down_revision = "6ba43edbc8b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
