"""Unique column book reader combination

Revision ID: 4f2b7c1a828f
Revises: 39d811a319e9
Create Date: 2022-07-24 15:40:27.487792

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4f2b7c1a828f"
down_revision = "39d811a319e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uc_books_readers_book_reader", "books_readers", ["book", "reader"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uc_books_readers_book_reader", "books_readers", type_="unique")
    # ### end Alembic commands ###
