"""last name to readers

Revision ID: 58110040ec1b
Revises: ca412443b884
Create Date: 2022-07-23 18:28:32.120365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58110040ec1b'
down_revision = 'ca412443b884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('lastname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readers', 'lastname')
    # ### end Alembic commands ###
