"""Readers

Revision ID: 6165962fd18b
Revises: 4b8504792353
Create Date: 2022-07-18 20:07:40.829745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6165962fd18b'
down_revision = '4b8504792353'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('books', sa.Column('reader', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_books_readers_id_reader', 'books', 'readers', ['reader'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_books_readers_id_reader', 'books', type_='foreignkey')
    op.drop_column('books', 'reader')
    op.drop_table('readers')
    # ### end Alembic commands ###
