"""foreign key as int

Revision ID: 6ba43edbc8b1
Revises: d04fc60aa73c
Create Date: 2022-07-24 15:11:49.893414

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ba43edbc8b1"
down_revision = "d04fc60aa73c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
