"""Books readers

Revision ID: 942d122658c3
Revises: 58110040ec1b
Create Date: 2022-07-24 15:01:32.280709

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "942d122658c3"
down_revision = "58110040ec1b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books_readers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("books", sa.Integer(), nullable=False),
        sa.Column("reader", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["books"], ["books.id"], name="fk_books_readers_books_id_books"
        ),
        sa.ForeignKeyConstraint(
            ["reader"], ["readers.id"], name="fk_books_readers_readers_id_reader"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("fk_books_readers_id_reader", "books", type_="foreignkey")
    op.drop_column("books", "reader")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("reader", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "fk_books_readers_id_reader", "books", "readers", ["reader"], ["id"]
    )
    op.drop_table("books_readers")
    # ### end Alembic commands ###
