"""nullable and indexed reader

Revision ID: b74b41acb90f
Revises: 6165962fd18b
Create Date: 2022-07-18 20:27:17.130568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74b41acb90f'
down_revision = '6165962fd18b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
