"""Book to Books

Revision ID: ca412443b884
Revises: b74b41acb90f
Create Date: 2022-07-19 20:52:06.445988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca412443b884'
down_revision = 'b74b41acb90f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
