"""rename books to book

Revision ID: d04fc60aa73c
Revises: 942d122658c3
Create Date: 2022-07-24 15:08:46.370215

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d04fc60aa73c"
down_revision = "942d122658c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books_readers", sa.Column("book", sa.Integer(), nullable=False))
    op.drop_constraint(
        "fk_books_readers_books_id_books", "books_readers", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_books_readers_books_id_book", "books_readers", "books", ["book"], ["id"]
    )
    op.drop_column("books_readers", "books")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books_readers",
        sa.Column("books", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "fk_books_readers_books_id_book", "books_readers", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_books_readers_books_id_books", "books_readers", "books", ["books"], ["id"]
    )
    op.drop_column("books_readers", "book")
    # ### end Alembic commands ###
